# Generated by Django 3.1 on 2020-11-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.task'),
        ),
    ]
