# Generated by Django 3.1 on 2020-11-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20201109_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
